name: Deploy to firebase production

on:
  release:
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - run: cd frontend/app && npm run build
      deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: FirebaseExtended/action-hosting-deploy@v0
          with:
            entryPath: "./Frontend/app"
            repoToken: "${{ secrets.GITHUB_TOKEN }}"
            firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
            projectId: chill-and-chat-9d33c
