name: Lint Codebase
on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    name: Lint Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Check code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint codebase
        uses: github/super-linter@v4.8.4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
