name: Format code using prettier
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
    
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: npm install -g prettier
      - run: npm run format
      - run: npm uninstall -g prettier
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatically format code
          branch: ${{ github.head_ref }}
